#!/usr/bin/env bash
set -e

candidates=$(grep -e '^\[' ~/.aws/credentials | sed -e 's/\[\(.*\)]/\1/g' | grep -v '^default$' | grep -v '\-mfa$' | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g')
echo "Candidates (${candidates})"
echo -n "Enter your profile: "
read -r PROFILE

echo -n "Enter your multi-factor authentication code: "
read -r TOKEN_CODE

SERIAL_NUMBER=$(aws iam list-mfa-devices --profile $PROFILE | jq -r '.MFADevices[0].SerialNumber')
MFA_PROFILE="${PROFILE}-mfa"
REGION=$(aws configure get region --profile "$PROFILE" --output text)

STS_CREDENTIALS=$(aws sts get-session-token \
  --serial-number "$SERIAL_NUMBER" \
  --token-code "$TOKEN_CODE" \
  --query "Credentials" \
  --profile "$PROFILE" \
  --output json)

aws configure set aws_access_key_id "$(echo "$STS_CREDENTIALS" | jq -r '.AccessKeyId')" --profile "$MFA_PROFILE"
aws configure set aws_secret_access_key "$(echo "$STS_CREDENTIALS" | jq -r '.SecretAccessKey')" --profile "$MFA_PROFILE"
aws configure set aws_session_token "$(echo "$STS_CREDENTIALS" | jq -r '.SessionToken')" --profile "$MFA_PROFILE"
aws configure set region "$REGION" --profile "$MFA_PROFILE"
aws configure set output json --profile "$MFA_PROFILE"

echo "AWS Profile, ${MFA_PROFILE}, has been saved to your config file."
